// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upload_event.proto

package rs.ac.ftn.isa.isabackend.proto;

public final class UploadEventProto {
  private UploadEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UploadEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rs.ac.ftn.isa.isabackend.proto.UploadEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 video_id = 1;</code>
     * @return The videoId.
     */
    long getVideoId();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string file_name = 3;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>string file_name = 3;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>int64 file_size_bytes = 4;</code>
     * @return The fileSizeBytes.
     */
    long getFileSizeBytes();

    /**
     * <code>string author_username = 5;</code>
     * @return The authorUsername.
     */
    java.lang.String getAuthorUsername();
    /**
     * <code>string author_username = 5;</code>
     * @return The bytes for authorUsername.
     */
    com.google.protobuf.ByteString
        getAuthorUsernameBytes();

    /**
     * <code>string upload_timestamp = 6;</code>
     * @return The uploadTimestamp.
     */
    java.lang.String getUploadTimestamp();
    /**
     * <code>string upload_timestamp = 6;</code>
     * @return The bytes for uploadTimestamp.
     */
    com.google.protobuf.ByteString
        getUploadTimestampBytes();

    /**
     * <code>string video_format = 7;</code>
     * @return The videoFormat.
     */
    java.lang.String getVideoFormat();
    /**
     * <code>string video_format = 7;</code>
     * @return The bytes for videoFormat.
     */
    com.google.protobuf.ByteString
        getVideoFormatBytes();

    /**
     * <code>string location = 8;</code>
     * @return The location.
     */
    java.lang.String getLocation();
    /**
     * <code>string location = 8;</code>
     * @return The bytes for location.
     */
    com.google.protobuf.ByteString
        getLocationBytes();

    /**
     * <code>double latitude = 9;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 10;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>int32 duration_seconds = 11;</code>
     * @return The durationSeconds.
     */
    int getDurationSeconds();

    /**
     * <code>string description = 12;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 12;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code rs.ac.ftn.isa.isabackend.proto.UploadEvent}
   */
  public static final class UploadEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rs.ac.ftn.isa.isabackend.proto.UploadEvent)
      UploadEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadEvent.newBuilder() to construct.
    private UploadEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadEvent() {
      title_ = "";
      fileName_ = "";
      authorUsername_ = "";
      uploadTimestamp_ = "";
      videoFormat_ = "";
      location_ = "";
      description_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UploadEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              videoId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 32: {

              fileSizeBytes_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              authorUsername_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              uploadTimestamp_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              videoFormat_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              location_ = s;
              break;
            }
            case 73: {

              latitude_ = input.readDouble();
              break;
            }
            case 81: {

              longitude_ = input.readDouble();
              break;
            }
            case 88: {

              durationSeconds_ = input.readInt32();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.ac.ftn.isa.isabackend.proto.UploadEventProto.internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.ac.ftn.isa.isabackend.proto.UploadEventProto.internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent.class, rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent.Builder.class);
    }

    public static final int VIDEO_ID_FIELD_NUMBER = 1;
    private long videoId_;
    /**
     * <code>int64 video_id = 1;</code>
     * @return The videoId.
     */
    @java.lang.Override
    public long getVideoId() {
      return videoId_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string file_name = 3;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string file_name = 3;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_SIZE_BYTES_FIELD_NUMBER = 4;
    private long fileSizeBytes_;
    /**
     * <code>int64 file_size_bytes = 4;</code>
     * @return The fileSizeBytes.
     */
    @java.lang.Override
    public long getFileSizeBytes() {
      return fileSizeBytes_;
    }

    public static final int AUTHOR_USERNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object authorUsername_;
    /**
     * <code>string author_username = 5;</code>
     * @return The authorUsername.
     */
    @java.lang.Override
    public java.lang.String getAuthorUsername() {
      java.lang.Object ref = authorUsername_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorUsername_ = s;
        return s;
      }
    }
    /**
     * <code>string author_username = 5;</code>
     * @return The bytes for authorUsername.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorUsernameBytes() {
      java.lang.Object ref = authorUsername_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPLOAD_TIMESTAMP_FIELD_NUMBER = 6;
    private volatile java.lang.Object uploadTimestamp_;
    /**
     * <code>string upload_timestamp = 6;</code>
     * @return The uploadTimestamp.
     */
    @java.lang.Override
    public java.lang.String getUploadTimestamp() {
      java.lang.Object ref = uploadTimestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uploadTimestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string upload_timestamp = 6;</code>
     * @return The bytes for uploadTimestamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUploadTimestampBytes() {
      java.lang.Object ref = uploadTimestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uploadTimestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIDEO_FORMAT_FIELD_NUMBER = 7;
    private volatile java.lang.Object videoFormat_;
    /**
     * <code>string video_format = 7;</code>
     * @return The videoFormat.
     */
    @java.lang.Override
    public java.lang.String getVideoFormat() {
      java.lang.Object ref = videoFormat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        videoFormat_ = s;
        return s;
      }
    }
    /**
     * <code>string video_format = 7;</code>
     * @return The bytes for videoFormat.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVideoFormatBytes() {
      java.lang.Object ref = videoFormat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videoFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 8;
    private volatile java.lang.Object location_;
    /**
     * <code>string location = 8;</code>
     * @return The location.
     */
    @java.lang.Override
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>string location = 8;</code>
     * @return The bytes for location.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 9;
    private double latitude_;
    /**
     * <code>double latitude = 9;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 10;
    private double longitude_;
    /**
     * <code>double longitude = 10;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    public static final int DURATION_SECONDS_FIELD_NUMBER = 11;
    private int durationSeconds_;
    /**
     * <code>int32 duration_seconds = 11;</code>
     * @return The durationSeconds.
     */
    @java.lang.Override
    public int getDurationSeconds() {
      return durationSeconds_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 12;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 12;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 12;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (videoId_ != 0L) {
        output.writeInt64(1, videoId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileName_);
      }
      if (fileSizeBytes_ != 0L) {
        output.writeInt64(4, fileSizeBytes_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authorUsername_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, authorUsername_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uploadTimestamp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, uploadTimestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(videoFormat_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, videoFormat_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(location_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, location_);
      }
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        output.writeDouble(9, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        output.writeDouble(10, longitude_);
      }
      if (durationSeconds_ != 0) {
        output.writeInt32(11, durationSeconds_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, description_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (videoId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, videoId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileName_);
      }
      if (fileSizeBytes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, fileSizeBytes_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authorUsername_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, authorUsername_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uploadTimestamp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, uploadTimestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(videoFormat_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, videoFormat_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(location_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, location_);
      }
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, longitude_);
      }
      if (durationSeconds_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, durationSeconds_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent)) {
        return super.equals(obj);
      }
      rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent other = (rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent) obj;

      if (getVideoId()
          != other.getVideoId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (getFileSizeBytes()
          != other.getFileSizeBytes()) return false;
      if (!getAuthorUsername()
          .equals(other.getAuthorUsername())) return false;
      if (!getUploadTimestamp()
          .equals(other.getUploadTimestamp())) return false;
      if (!getVideoFormat()
          .equals(other.getVideoFormat())) return false;
      if (!getLocation()
          .equals(other.getLocation())) return false;
      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (getDurationSeconds()
          != other.getDurationSeconds()) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VIDEO_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVideoId());
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILE_SIZE_BYTES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileSizeBytes());
      hash = (37 * hash) + AUTHOR_USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorUsername().hashCode();
      hash = (37 * hash) + UPLOAD_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getUploadTimestamp().hashCode();
      hash = (37 * hash) + VIDEO_FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getVideoFormat().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + DURATION_SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + getDurationSeconds();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rs.ac.ftn.isa.isabackend.proto.UploadEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rs.ac.ftn.isa.isabackend.proto.UploadEvent)
        rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rs.ac.ftn.isa.isabackend.proto.UploadEventProto.internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rs.ac.ftn.isa.isabackend.proto.UploadEventProto.internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent.class, rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent.Builder.class);
      }

      // Construct using rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        videoId_ = 0L;

        title_ = "";

        fileName_ = "";

        fileSizeBytes_ = 0L;

        authorUsername_ = "";

        uploadTimestamp_ = "";

        videoFormat_ = "";

        location_ = "";

        latitude_ = 0D;

        longitude_ = 0D;

        durationSeconds_ = 0;

        description_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rs.ac.ftn.isa.isabackend.proto.UploadEventProto.internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_descriptor;
      }

      @java.lang.Override
      public rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent getDefaultInstanceForType() {
        return rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent.getDefaultInstance();
      }

      @java.lang.Override
      public rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent build() {
        rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent buildPartial() {
        rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent result = new rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent(this);
        result.videoId_ = videoId_;
        result.title_ = title_;
        result.fileName_ = fileName_;
        result.fileSizeBytes_ = fileSizeBytes_;
        result.authorUsername_ = authorUsername_;
        result.uploadTimestamp_ = uploadTimestamp_;
        result.videoFormat_ = videoFormat_;
        result.location_ = location_;
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        result.durationSeconds_ = durationSeconds_;
        result.description_ = description_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent) {
          return mergeFrom((rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent other) {
        if (other == rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent.getDefaultInstance()) return this;
        if (other.getVideoId() != 0L) {
          setVideoId(other.getVideoId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getFileSizeBytes() != 0L) {
          setFileSizeBytes(other.getFileSizeBytes());
        }
        if (!other.getAuthorUsername().isEmpty()) {
          authorUsername_ = other.authorUsername_;
          onChanged();
        }
        if (!other.getUploadTimestamp().isEmpty()) {
          uploadTimestamp_ = other.uploadTimestamp_;
          onChanged();
        }
        if (!other.getVideoFormat().isEmpty()) {
          videoFormat_ = other.videoFormat_;
          onChanged();
        }
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          onChanged();
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getDurationSeconds() != 0) {
          setDurationSeconds(other.getDurationSeconds());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long videoId_ ;
      /**
       * <code>int64 video_id = 1;</code>
       * @return The videoId.
       */
      @java.lang.Override
      public long getVideoId() {
        return videoId_;
      }
      /**
       * <code>int64 video_id = 1;</code>
       * @param value The videoId to set.
       * @return This builder for chaining.
       */
      public Builder setVideoId(long value) {
        
        videoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 video_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideoId() {
        
        videoId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string file_name = 3;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string file_name = 3;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file_name = 3;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 3;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private long fileSizeBytes_ ;
      /**
       * <code>int64 file_size_bytes = 4;</code>
       * @return The fileSizeBytes.
       */
      @java.lang.Override
      public long getFileSizeBytes() {
        return fileSizeBytes_;
      }
      /**
       * <code>int64 file_size_bytes = 4;</code>
       * @param value The fileSizeBytes to set.
       * @return This builder for chaining.
       */
      public Builder setFileSizeBytes(long value) {
        
        fileSizeBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 file_size_bytes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSizeBytes() {
        
        fileSizeBytes_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object authorUsername_ = "";
      /**
       * <code>string author_username = 5;</code>
       * @return The authorUsername.
       */
      public java.lang.String getAuthorUsername() {
        java.lang.Object ref = authorUsername_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authorUsername_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string author_username = 5;</code>
       * @return The bytes for authorUsername.
       */
      public com.google.protobuf.ByteString
          getAuthorUsernameBytes() {
        java.lang.Object ref = authorUsername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authorUsername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string author_username = 5;</code>
       * @param value The authorUsername to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authorUsername_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string author_username = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorUsername() {
        
        authorUsername_ = getDefaultInstance().getAuthorUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string author_username = 5;</code>
       * @param value The bytes for authorUsername to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authorUsername_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uploadTimestamp_ = "";
      /**
       * <code>string upload_timestamp = 6;</code>
       * @return The uploadTimestamp.
       */
      public java.lang.String getUploadTimestamp() {
        java.lang.Object ref = uploadTimestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uploadTimestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string upload_timestamp = 6;</code>
       * @return The bytes for uploadTimestamp.
       */
      public com.google.protobuf.ByteString
          getUploadTimestampBytes() {
        java.lang.Object ref = uploadTimestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uploadTimestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string upload_timestamp = 6;</code>
       * @param value The uploadTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setUploadTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uploadTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string upload_timestamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUploadTimestamp() {
        
        uploadTimestamp_ = getDefaultInstance().getUploadTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>string upload_timestamp = 6;</code>
       * @param value The bytes for uploadTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setUploadTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uploadTimestamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object videoFormat_ = "";
      /**
       * <code>string video_format = 7;</code>
       * @return The videoFormat.
       */
      public java.lang.String getVideoFormat() {
        java.lang.Object ref = videoFormat_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          videoFormat_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string video_format = 7;</code>
       * @return The bytes for videoFormat.
       */
      public com.google.protobuf.ByteString
          getVideoFormatBytes() {
        java.lang.Object ref = videoFormat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videoFormat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string video_format = 7;</code>
       * @param value The videoFormat to set.
       * @return This builder for chaining.
       */
      public Builder setVideoFormat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        videoFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string video_format = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideoFormat() {
        
        videoFormat_ = getDefaultInstance().getVideoFormat();
        onChanged();
        return this;
      }
      /**
       * <code>string video_format = 7;</code>
       * @param value The bytes for videoFormat to set.
       * @return This builder for chaining.
       */
      public Builder setVideoFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        videoFormat_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>string location = 8;</code>
       * @return The location.
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string location = 8;</code>
       * @return The bytes for location.
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string location = 8;</code>
       * @param value The location to set.
       * @return This builder for chaining.
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string location = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocation() {
        
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <code>string location = 8;</code>
       * @param value The bytes for location to set.
       * @return This builder for chaining.
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        location_ = value;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 9;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 9;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 10;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 10;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private int durationSeconds_ ;
      /**
       * <code>int32 duration_seconds = 11;</code>
       * @return The durationSeconds.
       */
      @java.lang.Override
      public int getDurationSeconds() {
        return durationSeconds_;
      }
      /**
       * <code>int32 duration_seconds = 11;</code>
       * @param value The durationSeconds to set.
       * @return This builder for chaining.
       */
      public Builder setDurationSeconds(int value) {
        
        durationSeconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 duration_seconds = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearDurationSeconds() {
        
        durationSeconds_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 12;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 12;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 12;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 12;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rs.ac.ftn.isa.isabackend.proto.UploadEvent)
    }

    // @@protoc_insertion_point(class_scope:rs.ac.ftn.isa.isabackend.proto.UploadEvent)
    private static final rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent();
    }

    public static rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadEvent>
        PARSER = new com.google.protobuf.AbstractParser<UploadEvent>() {
      @java.lang.Override
      public UploadEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rs.ac.ftn.isa.isabackend.proto.UploadEventProto.UploadEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022upload_event.proto\022\036rs.ac.ftn.isa.isab" +
      "ackend.proto\"\211\002\n\013UploadEvent\022\020\n\010video_id" +
      "\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\021\n\tfile_name\030\003 \001(\t" +
      "\022\027\n\017file_size_bytes\030\004 \001(\003\022\027\n\017author_user" +
      "name\030\005 \001(\t\022\030\n\020upload_timestamp\030\006 \001(\t\022\024\n\014" +
      "video_format\030\007 \001(\t\022\020\n\010location\030\010 \001(\t\022\020\n\010" +
      "latitude\030\t \001(\001\022\021\n\tlongitude\030\n \001(\001\022\030\n\020dur" +
      "ation_seconds\030\013 \001(\005\022\023\n\013description\030\014 \001(\t" +
      "B2\n\036rs.ac.ftn.isa.isabackend.protoB\020Uplo" +
      "adEventProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rs_ac_ftn_isa_isabackend_proto_UploadEvent_descriptor,
        new java.lang.String[] { "VideoId", "Title", "FileName", "FileSizeBytes", "AuthorUsername", "UploadTimestamp", "VideoFormat", "Location", "Latitude", "Longitude", "DurationSeconds", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
